
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    "app.kubernetes.io/instance": "quarkus-demo2"
    "app.openshift.io/runtime": "quarkus"
    "boson.dev/function": "true"
    "boson.dev/runtime": "quarkus"
    "function.knative.dev": "true"
    "function.knative.dev/name": "quarkus-demo2"
    "function.knative.dev/runtime": "quarkus"
    
    tekton.dev/pipeline: quarkus-demo2-pack-git-pipeline
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[push]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # Fetch the git-clone task from hub
    pipelinesascode.tekton.dev/task: git-clone

    # Fetch the func-buildpacks task
    pipelinesascode.tekton.dev/task-1: https://raw.githubusercontent.com/openshift-knative/kn-plugin-func/serverless-1.31/pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml

    # Fetch the func-deploy task
    pipelinesascode.tekton.dev/task-2: https://raw.githubusercontent.com/openshift-knative/kn-plugin-func/serverless-1.31/pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy-pac.yaml

    # Fetch the pipelie definition from the .tekton directory
    pipelinesascode.tekton.dev/pipeline: .tekton/pipeline-pac.yaml

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "5"

    # User defined Annotations
    
  generateName: quarkus-demo2-pack-git-pipeline-run
spec:
  params:
    - name: gitRepository
      value: {{ repo_url }}
    - name: gitRevision
      value: {{ revision }}
    - name: contextDir
      value: 
    - name: imageName
      value: quay.io/mvinkler/quarkus-demo2:latest
    - name: registry
      value: quay.io/mvinkler
    - name: builderImage
      value: ghcr.io/knative/builder-jammy-tiny:latest
    - name: buildEnvs
      value:
        - BP_JVM_VERSION=17
        - BP_NATIVE_IMAGE=false
        - BP_MAVEN_BUILT_ARTIFACT=func.yaml target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/
        - BP_MAVEN_BUILD_ARGUMENTS=package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar
        - MAVEN_S2I_ARTIFACT_DIRS=target/quarkus-app
        - S2I_SOURCE_DEPLOYMENTS_FILTER=lib quarkus-run.jar app quarkus
        
  pipelineRef:
   name: quarkus-demo2-pack-git-pipeline
  workspaces:
    - name: source-workspace
      persistentVolumeClaim:
        claimName: quarkus-demo2-pack-git-pipeline-pvc
      subPath: source
    - name: cache-workspace
      persistentVolumeClaim:
        claimName: quarkus-demo2-pack-git-pipeline-pvc
      subPath: cache
    - name: dockerconfig-workspace
      secret:
        secretName: quarkus-demo2-pack-git-pipeline-secret
